{
 "title": "Battle of Galen Erso Dashboard",
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "memused", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Memory free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "memfree", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Mempool size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "mempool_size", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "blocks", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "TX rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "txrate", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "UTXO set size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "utxosetsize", "legendFormat": "{{pod}}" }
   ]
  }
 ]
}